spring:
  application:
    name: pa-simulator
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pa}
    username: ${SPRING_DATASOURCE_USERNAME:pa}
    password: ${SPRING_DATASOURCE_PASSWORD:pa}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

logging:
  level:
    fr.pa.simulator: DEBUG
